// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwhD6fawTjhZlbC9j5pKxAg6x0oTWIFYY',
    appId: '1:182769311613:web:59f66211b29ce90ea5f614',
    messagingSenderId: '182769311613',
    projectId: 'project1-e4867',
    authDomain: 'project1-e4867.firebaseapp.com',
    storageBucket: 'project1-e4867.firebasestorage.app',
    measurementId: 'G-C712CF4709',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPnPcrXYVZLepDJJB07AEf4-wJlu1qrGI',
    appId: '1:182769311613:android:fab592011c60022ea5f614',
    messagingSenderId: '182769311613',
    projectId: 'project1-e4867',
    storageBucket: 'project1-e4867.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB01s4_rvZn26qIKNfrgSvrG78RtegDC08',
    appId: '1:182769311613:ios:fa1f73eb6b7473ada5f614',
    messagingSenderId: '182769311613',
    projectId: 'project1-e4867',
    storageBucket: 'project1-e4867.firebasestorage.app',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB01s4_rvZn26qIKNfrgSvrG78RtegDC08',
    appId: '1:182769311613:ios:fa1f73eb6b7473ada5f614',
    messagingSenderId: '182769311613',
    projectId: 'project1-e4867',
    storageBucket: 'project1-e4867.firebasestorage.app',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwhD6fawTjhZlbC9j5pKxAg6x0oTWIFYY',
    appId: '1:182769311613:web:54838a9c2e79cfaaa5f614',
    messagingSenderId: '182769311613',
    projectId: 'project1-e4867',
    authDomain: 'project1-e4867.firebaseapp.com',
    storageBucket: 'project1-e4867.firebasestorage.app',
    measurementId: 'G-MZ2DNQ7X2M',
  );

}