// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDvX_l1aCTh9V3qN_PNJbrl1NB1su_5y4',
    appId: '1:18547901578:web:4ed656af2547d54bcd5973',
    messagingSenderId: '18547901578',
    projectId: 'project2-aditya-kareliya',
    authDomain: 'project2-aditya-kareliya.firebaseapp.com',
    storageBucket: 'project2-aditya-kareliya.firebasestorage.app',
    measurementId: 'G-N5WLB99SPR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdRbbDnmhtp_9t4UI04HmO1ol6IAepzXs',
    appId: '1:18547901578:android:4886277565123720cd5973',
    messagingSenderId: '18547901578',
    projectId: 'project2-aditya-kareliya',
    storageBucket: 'project2-aditya-kareliya.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLudIlM106gNf4GCGbGZFX8CVQLX9Gk54',
    appId: '1:18547901578:ios:88df9841b01de279cd5973',
    messagingSenderId: '18547901578',
    projectId: 'project2-aditya-kareliya',
    storageBucket: 'project2-aditya-kareliya.firebasestorage.app',
    iosBundleId: 'com.example.expenseTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLudIlM106gNf4GCGbGZFX8CVQLX9Gk54',
    appId: '1:18547901578:ios:88df9841b01de279cd5973',
    messagingSenderId: '18547901578',
    projectId: 'project2-aditya-kareliya',
    storageBucket: 'project2-aditya-kareliya.firebasestorage.app',
    iosBundleId: 'com.example.expenseTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDvX_l1aCTh9V3qN_PNJbrl1NB1su_5y4',
    appId: '1:18547901578:web:f161803fadfcc9a2cd5973',
    messagingSenderId: '18547901578',
    projectId: 'project2-aditya-kareliya',
    authDomain: 'project2-aditya-kareliya.firebaseapp.com',
    storageBucket: 'project2-aditya-kareliya.firebasestorage.app',
    measurementId: 'G-ST71GXN7XQ',
  );
}
